import { hash } from "bcryptjs";
import { PrismaClient, RuleSourceType } from "@prisma/client";

const db = new PrismaClient();
const categories = [
  ["A", "Pro hašení a čerpání", ["Hasicí", "Přívodního vedení", "Výtlačného vedení", "Pěnotvorné"]],
  ["B", "Pro technické činnosti", ["Pneumatické vyprošťovací a těsnicí", "Osvětlovací a varovné", "Vyprošťovací a destrukční", "Evakuační", "První pomoci", "Přenosné žebříky", "Ostatní účelové"]],
  ["C", "Pro práci ve výšce a nad volnou hloubkou", ["Lana", "Pásy a postroje", "Ostatní textilní materiál", "Karabiny a spojky", "Ostatní kovový materiál", "Prostředky pro vytahování a spouštění", "Ochranné", "Ostatní"]],
  ["D", "Pro práci na vodní hladině", ["Záchranná plavidla", "Vybavení plavidel", "Záchranné", "Ochranné", "K vyhledávání", "Norné stěny", "Protipovodňové"]],
  ["E", "Ochranné pro hasiče", ["Ve výhradním užívání", "Společné"]],
] as const;

async function main(){const organization=await db.organization.upsert({where:{name:"HZS ČEPRO"},update:{},create:{name:"HZS ČEPRO"}});const station=await db.station.upsert({where:{organizationId_name:{organizationId:organization.id,name:"Mstětice"}},update:{},create:{name:"Mstětice",organizationId:organization.id}});const root=await db.location.findFirst({where:{stationId:station.id,parentId:null,name:"Stanice"}})??await db.location.create({data:{name:"Stanice",stationId:station.id}});for(const name of ["Sklad TS","Dílna","Sklad","Garáž"])await db.location.createMany({data:[{name,stationId:station.id,parentId:root.id}],skipDuplicates:true});
  const categoryIds=new Map<string,string>();for(const[code,name,children]of categories){const parent=await db.equipmentCategory.upsert({where:{code},update:{name},create:{code,name}});categoryIds.set(name,parent.id);for(const[order,child]of children.entries()){const childCode=`${code}.${order+1}`;const row=await db.equipmentCategory.upsert({where:{code:childCode},update:{name:child},create:{code:childCode,name:child,parentId:parent.id}});categoryIds.set(child,row.id)}}
  const source=await db.sourceDocument.findFirst({where:{documentNumber:"62/2016"}})??await db.sourceDocument.create({data:{title:"Pokyn generálního ředitele HZS ČR – Řád technické služby HZS ČR",documentNumber:"62/2016",sourceType:RuleSourceType.TECHNICAL_SERVICE_ORDER}});for(const[name,months]of [["První pomoci",6],["Pro práci ve výšce a nad volnou hloubkou",12],["Pneumatické vyprošťovací a těsnicí",12]] as const){const categoryId=categoryIds.get(name);if(!categoryId)continue;const existing=await db.rule.findFirst({where:{name:`Pravidelná kontrola – ${name}`,sourceDocumentId:source.id}});if(!existing)await db.rule.create({data:{name:`Pravidelná kontrola – ${name}`,requirementType:"INSPECTION",sourceType:"TECHNICAL_SERVICE_ORDER",sourceDocumentId:source.id,categoryId,versions:{create:{version:1,validFrom:new Date("2016-12-01T00:00:00Z"),intervalValue:months,intervalUnit:"MONTHS",note:"Platí, pokud výrobce nestanovil kratší interval."}}}})}
  const template=await db.checklistTemplate.findFirst({where:{name:"Obecná kontrola prostředku"}})??await db.checklistTemplate.create({data:{name:"Obecná kontrola prostředku",versions:{create:{version:1,sections:{create:[{title:"Vizuální kontrola",sortOrder:1,items:{create:["Celistvost","Úplnost","Známky poškození","Čitelnost označení","Kompletnost příslušenství"].map((label,sortOrder)=>({label,responseType:"PASS_FAIL_NA",required:true,failRequiresNote:true,failCreatesDefect:true,sortOrder}))}},{title:"Funkční kontrola",sortOrder:2,items:{create:["Správný chod","Ovládání","Funkčnost"].map((label,sortOrder)=>({label,responseType:"PASS_FAIL_NA",required:true,failRequiresNote:true,failCreatesDefect:true,sortOrder}))}}]}}}}});void template;
  const roles=[["ADMIN","Administrátor"],["TS_ADMIN","Vedoucí technické služby"],["TECHNICIAN","Technik"],["USER","Uživatel"]] as const;for(const[code,name]of roles)await db.role.upsert({where:{code},update:{name},create:{code,name}});const username=process.env.INITIAL_ADMIN_USERNAME;const password=process.env.INITIAL_ADMIN_PASSWORD;if(username&&password){const exists=await db.user.findUnique({where:{username}});if(!exists){const admin=await db.role.findUniqueOrThrow({where:{code:"ADMIN"}});await db.user.create({data:{username,displayName:"Administrátor",passwordHash:await hash(password,12),organizationId:organization.id,roles:{create:{roleId:admin.id}}}})}}
}
main().finally(()=>db.$disconnect());
